# 5장. 분석을 믿을 수 있게 만드는 데이터 전처리

이 노트북은 `book/chapters/ch05_data_preprocessing.md` 강의안을 초보자가 그대로 따라 하며 이해할 수 있도록 구성한 실습 자료입니다.

이번 장의 핵심은 데이터를 무조건 깨끗하게 만드는 것이 아니라, 분석 결과를 신뢰할 수 있도록 데이터의 상태를 확인하고 처리 기준을 남기는 것입니다.

## 0. 제출 정보
- 이름: 유은송
- GitHub ID: song-03
- 작성일: 2026.10.14. 
- 최종 제출 URL: https://github.com/song-03/llm-data-analysis-study/blob/main/chapter05/chapter05.ipynb
- 이 과제는 교수님 레포지토리(course)를 로컬에 복제해 실행하고 이 제출 레포지토리에는 실행 결과가 남은 Notebook과 캡처 이미지, reports만 업로드함

##### 0. 이 노트북 사용 방법

아래 셀을 위에서부터 차례대로 실행하세요.

- 원본 데이터는 `data/raw/`에 그대로 둡니다.
- 전처리 결과는 `data/processed/`에 별도로 저장합니다.
- 전처리 요약 보고서는 `reports/ch05_preprocessing_summary.md`에 저장합니다.
- 코드가 실행되었다고 끝이 아니라, 처리 기준을 설명할 수 있어야 합니다.

##### 1. 왜 전처리가 필요한가

현실의 데이터는 처음부터 분석하기 좋은 형태로 주어지지 않습니다.

예를 들어 다음과 같은 문제가 있을 수 있습니다.

| 문제 유형 | 예시 | 확인할 질문 |
|---|---|---|
| 결측치 | 나이가 비어 있는 고객 | 비어 있는 이유가 무엇인가? 삭제해도 되는가? |
| 중복 | 같은 고객 ID가 여러 번 등장 | 자연스러운 중복인가, 데이터 오류인가? |
| 타입 오류 | 가격이 문자열로 저장됨 | 계산 가능한 숫자형으로 바꿀 수 있는가? |
| 날짜 오류 | 주문일이 문자열로 저장됨 | 월별·요일별 분석에 사용할 수 있는가? |
| 문자열 표기 차이 | `Seoul`, ` Seoul`, `SEOUL` | 같은 값을 하나의 표기로 통일해야 하는가? |
| 이상값 | 수량이 음수이거나 가격이 0원 | 실제 의미가 있는 값인가, 입력 오류인가? |
| 파생 컬럼 필요 | 수량과 단가만 있고 주문금액이 없음 | 분석에 필요한 새 컬럼을 만들 수 있는가? |

##### 2. 원본 데이터와 전처리 데이터 분리하기

전처리에서 가장 중요한 원칙은 원본 데이터를 직접 덮어쓰지 않는 것입니다.

```text
data/
├─ raw/
│  ├─ customers.csv
│  ├─ products.csv
│  ├─ orders.csv
│  └─ order_items.csv
└─ processed/
   ├─ customers_clean.csv
   ├─ products_clean.csv
   ├─ orders_clean.csv
   └─ order_items_clean.csv
```

원본과 전처리 결과를 분리하면 실수했을 때 원본으로 돌아갈 수 있고, 전처리 전후 차이를 비교할 수 있습니다.

##### 3. 패키지와 경로 설정

노트북이 `notebooks/` 폴더 안에서 실행되는 경우와 프로젝트 루트에서 실행되는 경우를 모두 고려해 경로를 설정합니다.

In [1]:
from pathlib import Path
import sys

import pandas as pd
import numpy as np

CURRENT_DIR = Path.cwd()

if CURRENT_DIR.name == 'notebooks':
    PROJECT_ROOT = CURRENT_DIR.parent
else:
    PROJECT_ROOT = CURRENT_DIR

RAW_DIR = PROJECT_ROOT / 'practice' / 'chapter05' / 'data' / 'raw' 
PROCESSED_DIR = PROJECT_ROOT / 'data' / 'processed'
REPORT_DIR = PROJECT_ROOT / 'reports'

PROCESSED_DIR.mkdir(parents=True, exist_ok=True)
REPORT_DIR.mkdir(exist_ok=True)

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

print('현재 실행 위치:', CURRENT_DIR)
print('프로젝트 루트:', PROJECT_ROOT)
print('원본 데이터 폴더:', RAW_DIR)
print('전처리 데이터 폴더:', PROCESSED_DIR)
print('보고서 폴더:', REPORT_DIR)

현재 실행 위치: c:\dev\llm-data-analysis-course\notebooks
프로젝트 루트: c:\dev\llm-data-analysis-course
원본 데이터 폴더: c:\dev\llm-data-analysis-course\practice\chapter05\data\raw
전처리 데이터 폴더: c:\dev\llm-data-analysis-course\data\processed
보고서 폴더: c:\dev\llm-data-analysis-course\reports

##### 4. 원본 데이터 불러오기

이번 장에서는 온라인 쇼핑몰 예제 데이터 4개를 사용합니다.

- `customers.csv`: 고객 정보
- `products.csv`: 상품 정보
- `orders.csv`: 주문 정보
- `order_items.csv`: 주문 상세 정보

In [2]:
customers = pd.read_csv(RAW_DIR / 'customers.csv')
products = pd.read_csv(RAW_DIR / 'products.csv')
orders = pd.read_csv(RAW_DIR / 'orders.csv')
order_items = pd.read_csv(RAW_DIR / 'order_items.csv')

print('원본 데이터 불러오기 완료')

원본 데이터 불러오기 완료

##### 5. 전처리 전 데이터 크기 기록하기

전처리 전 데이터 크기를 기록해 두면 나중에 어떤 데이터가 얼마나 바뀌었는지 비교할 수 있습니다.

In [3]:
raw_data = {
    'customers': customers,
    'products': products,
    'orders': orders,
    'order_items': order_items,
}

raw_shapes = pd.DataFrame({
    'dataset': list(raw_data.keys()),
    'rows': [df.shape[0] for df in raw_data.values()],
    'columns': [df.shape[1] for df in raw_data.values()],
})

raw_shapes

       dataset  rows  columns
0    customers   152        6
1     products   102        4
2       orders   302        5
3  order_items   765        5

In [4]:
for name, df in raw_data.items():
    print(f'[{name}]')
    print('shape:', df.shape)
    print('columns:', list(df.columns))
    print()

[customers]
shape: (152, 6)
columns: ['customer_id', 'name', 'gender', 'age', 'city', 'signup_date']

[products]
shape: (102, 4)
columns: ['product_id', 'product_name', 'category', 'price']

[orders]
shape: (302, 5)
columns: ['order_id', 'customer_id', 'order_date', 'payment_method', 'order_status']

[order_items]
shape: (765, 5)
columns: ['order_item_id', 'order_id', 'product_id', 'quantity', 'unit_price']

##### 6. 원본을 복사해서 전처리 시작하기

전처리 과정에서는 원본 DataFrame을 직접 수정하지 않고 복사본을 사용합니다.

In [5]:
customers_clean = customers.copy()
products_clean = products.copy()
orders_clean = orders.copy()
order_items_clean = order_items.copy()

clean_data = {
    'customers': customers_clean,
    'products': products_clean,
    'orders': orders_clean,
    'order_items': order_items_clean,
}

print('전처리용 복사본 생성 완료')

전처리용 복사본 생성 완료

##### 7. 결측치 확인하기

결측치를 처리하기 전에 먼저 어디에 얼마나 비어 있는 값이 있는지 확인합니다. 개수와 비율을 함께 보면 데이터 크기에 따른 차이를 이해하기 쉽습니다.

In [6]:
for name, df in clean_data.items():
    print(f'\n[{name}] 결측치 개수')
    print(df.isna().sum())

[customers] 결측치 개수
customer_id    0
name           0
gender         0
age            4
city           2
signup_date    0
dtype: int64

[products] 결측치 개수
product_id      0
product_name    0
category        0
price           0
dtype: int64

[orders] 결측치 개수
order_id          0
customer_id       0
order_date        0
payment_method    0
order_status      0
dtype: int64

[order_items] 결측치 개수
order_item_id    0
order_id         0
product_id       0
quantity         0
unit_price       0
dtype: int64

In [7]:
def missing_summary(df):
    summary = pd.DataFrame({
        'missing_count': df.isna().sum(),
        'missing_ratio': (df.isna().mean() * 100).round(2),
    })
    return summary.sort_values('missing_count', ascending=False)

missing_summary(customers_clean)

             missing_count  missing_ratio
age                      4           2.63
city                     2           1.32
name                     0           0.00
customer_id              0           0.00
gender                   0           0.00
signup_date              0           0.00

##### 8. 결측치 처리하기

결측치 처리는 컬럼의 의미에 따라 달라집니다.

- 나이처럼 숫자형 컬럼은 중앙값으로 대체할 수 있습니다.
- 도시처럼 범주형 컬럼은 `Unknown`으로 남겨 분석에서 구분할 수 있습니다.

실제 업무에서는 결측치가 왜 생겼는지 먼저 확인해야 합니다.

In [8]:
if 'age' in customers_clean.columns:
    customers_clean['age'] = pd.to_numeric(customers_clean['age'], errors='coerce')
    age_median = customers_clean['age'].median()
    customers_clean['age'] = customers_clean['age'].fillna(age_median)
    print('age 중앙값:', age_median)

if 'city' in customers_clean.columns:
    customers_clean['city'] = customers_clean['city'].fillna('Unknown')

missing_summary(customers_clean)

age 중앙값: 41.0

             missing_count  missing_ratio
customer_id              0            0.0
name                     0            0.0
gender                   0            0.0
age                      0            0.0
city                     0            0.0
signup_date              0            0.0

##### 9. 중복 확인하기

중복은 맥락에 따라 의미가 다릅니다. `customers`의 `customer_id` 중복은 오류일 가능성이 크지만, `order_items`의 `order_id` 반복은 한 주문에 여러 상품이 들어갈 수 있으므로 자연스럽습니다.

In [9]:
for name, df in clean_data.items():
    print(name, '전체 행 중복 수:', df.duplicated().sum())

customers 전체 행 중복 수: 2
products 전체 행 중복 수: 2
orders 전체 행 중복 수: 2
order_items 전체 행 중복 수: 2

In [10]:
key_checks = {
    'customers': ('customer_id', customers_clean),
    'products': ('product_id', products_clean),
    'orders': ('order_id', orders_clean),
    'order_items': ('order_item_id', order_items_clean),
}

for name, (key_col, df) in key_checks.items():
    if key_col in df.columns:
        print(name, key_col, '중복 수:', df[key_col].duplicated().sum())
    else:
        print(name, key_col, '컬럼 없음')

customers customer_id 중복 수: 2
products product_id 중복 수: 2
orders order_id 중복 수: 2
order_items order_item_id 중복 수: 2

In [11]:
#원본 type 확인
for name, df in raw_data.items():
    print(f'[{name}]')
    print(df.dtypes.to_dict())

[customers]
{'customer_id': dtype('int64'), 'name': <StringDtype(storage='python', na_value=nan)>, 'gender': <StringDtype(storage='python', na_value=nan)>, 'age': <StringDtype(storage='python', na_value=nan)>, 'city': <StringDtype(storage='python', na_value=nan)>, 'signup_date': <StringDtype(storage='python', na_value=nan)>}
[products]
{'product_id': dtype('int64'), 'product_name': <StringDtype(storage='python', na_value=nan)>, 'category': <StringDtype(storage='python', na_value=nan)>, 'price': <StringDtype(storage='python', na_value=nan)>}
[orders]
{'order_id': dtype('int64'), 'customer_id': dtype('int64'), 'order_date': <StringDtype(storage='python', na_value=nan)>, 'payment_method': <StringDtype(storage='python', na_value=nan)>, 'order_status': <StringDtype(storage='python', na_value=nan)>}
[order_items]
{'order_item_id': dtype('int64'), 'order_id': dtype('int64'), 'product_id': dtype('int64'), 'quantity': <StringDtype(storage='python', na_value=nan)>, 'unit_price': <StringDtype(storage='python', na_value=nan)>}

## 1. 전처리 전 상태 기록
- 각 데이터 shape: customers는 152행 6열, products는 102행 4열, orders는 302행 5열, order_items는 765행 5열 이다.
- 결측치: customers의 age 4건, city 2건이다. 나머지 3개 csv는 0건이다.
- 전체 중복: 4개 csv에 각각 2건씩 있다.
- 주요 ID 중복: customer_id, product_id, order_id, order_item_id 모두 2건씩 있다.
- 타입 문제 후보: customers.age, products.price, order_items.quantity, order_items.unit_price (숫자여야 하는데 문자열), customers.signup_date, orders.order_date (날짜인데 문자열)

![전처리 전 상태](images/step01_before.png)

### 결과 관찰
customers는 152행 6열, products는 102행 4열, orders는 302행 5열, order_items는 765행 5열이다. 결측치는 customers의 age에 4건, city에 2건이 있었고 나머지 데이터에는 없었다. 완전 중복 행은 4개 csv에 각각 2건씩 있었고, 주요 ID 중복도 각각 2건씩 있었다. 타입을 확인해보니 age, price, quantity, unit_price가 숫자가 아니라 문자열 dtype으로 읽혔다. customers.signup_date와 orders.order_date도 문자열 dtype이었다.

### 나의 해석과 판단
현재 원본 csv에서는 결측, 중복, 타입 문제가 모두 확인되었다. 숫자여야 하는 컬럼이 문자열로 읽혔다는 것은 숫자가 아닌 값이나 쉼표 같은 문자가 섞여 있을 가능성이 높다는 뜻이다. order_items에서 order_id가 반복되는 것은 하나의 주문에 여러 상품이 포함되는 관계에서 자연스럽게 발생할 수 있으므로, 주요 ID 중복과는 구분해서 봐야 한다.

가장 먼저 처리해야 하는 것은 완전 중복 제거와 문자열 정리, 그리고 형식 변환이다. 중복 행이 남아 있으면 이후 결측 건수나 집계 결과가 부풀려지고, 공백이나 문자가 섞인 상태에서는 숫자와 날짜 변환이 실패하기 때문이다. 특히 주문 월, 요일 분석에 필요한 orders.order_date와 금액 계산에 필요한 price, quantity, unit_price는 변환하는 과정에서 실패하는 값이 몇 건인지 반드시 확인해야 한다. 주요 ID 중복은 완전 중복과 같은 행인지 먼저 보고, 키만 같고 내용이 다른 경우라면 바로 삭제하지 않고 원인을 확인해야 한다.

### 업무·분석적 의미
전처리 전 기준선을 정해두면 이후 행 수, 결측값, 중복, 범주값의 변화가 의도한 처리 결과인지 확인할 수 있다. 이번처럼 원본에 문제가 있는 경우, 처리 후 몇 건이 줄었고 왜 줄었는지를 설명하는 근거가 된다. 특히 날짜를 정상적으로 변환해야 기간(ex. 월, 요일)별 주문 분석에서도 계산 범위를 정확하게 잡을 수 있다. 따라서 데이터를 본격적으로 분석하기 전 전처리가 필요한 항목들을 미리 확인해두는 것이 시간 절약 및 데이터 신뢰성에 도움이 된다.

### 한계와 추가 확인 사항
결측이나 문자가 섞인 값이 왜 생겼는지(단순 입력 누락인지, 시스템 오류인지)는 현재 데이터만으로 판단하기 어렵다. 완전 중복 행도 실제로 같은 기록이 두 번 저장된 것인지, 수집 과정에서 중복으로 들어온 것인지는 원본 시스템을 확인해야 한다. 또한 이 단계에서는 dtype만 확인했기 때문에, 실제로 몇 건이 변환에 실패하는지는 이후 STEP에서 확인해야 한다. (추후 step에서 진행)

In [12]:
customers_clean = customers_clean.drop_duplicates()
products_clean = products_clean.drop_duplicates()
orders_clean = orders_clean.drop_duplicates()
order_items_clean = order_items_clean.drop_duplicates()

print('완전 중복 행 제거 완료')

완전 중복 행 제거 완료

##### 10. 문자열 표기 정리하기

문자열 데이터에는 앞뒤 공백이 숨어 있을 수 있습니다. `Seoul`과 ` Seoul `은 눈으로는 비슷하지만 pandas에서는 서로 다른 값입니다.

결측치를 문자열 `nan`으로 바꾸지 않도록 주의하면서 문자열 컬럼의 앞뒤 공백을 제거합니다.

In [13]:
def strip_string_columns(df):
    result = df.copy()
    string_columns = result.select_dtypes(include=['object', 'str']).columns

    for col in string_columns:
        result[col] = result[col].where(
            result[col].isna(),
            result[col].astype(str).str.strip()
        )
        result[col] = result[col].replace('', pd.NA)  # 공백만 있던 값은 결측으로 인식

    return result

customers_clean = strip_string_columns(customers_clean)
products_clean = strip_string_columns(products_clean)
orders_clean = strip_string_columns(orders_clean)
order_items_clean = strip_string_columns(order_items_clean)

print('문자열 앞뒤 공백 제거 완료')

문자열 앞뒤 공백 제거 완료

In [14]:
if 'city' in customers_clean.columns:
    display(customers_clean['city'].value_counts().head(10))

if 'order_status' in orders_clean.columns:
    display(orders_clean['order_status'].value_counts())

city
부산    23
대구    21
광주    21
서울    18
울산    17
인천    16
수원    10
성남     9
고양     8
대전     5
Name: count, dtype: int64

order_status
completed    175
cancelled     58
refunded      52
Complete       2
cancel         2
Refund         2
complete       1
COMPLETED      1
완료             1
Cancel         1
CANCELLED      1
취소             1
refund         1
REFUNDED       1
환불             1
Name: count, dtype: int64

##### 11. 주문 상태값 통일하기

주문 상태값이 `complete`, `Complete`, `COMPLETED`, `완료`처럼 섞여 있으면 같은 상태를 서로 다른 값으로 집계할 수 있습니다. 대표 표기로 통일합니다.

In [15]:
status_map = {
    'complete': 'completed',
    'Complete': 'completed',
    'COMPLETED': 'completed',
    '완료': 'completed',
    'cancel': 'cancelled',
    'Cancel': 'cancelled',
    'CANCELLED': 'cancelled',
    '취소': 'cancelled',
    'refund': 'refunded',
    'Refund': 'refunded',
    'REFUNDED': 'refunded',
    '환불': 'refunded',
}

if 'order_status' in orders_clean.columns:
    orders_clean['order_status'] = orders_clean['order_status'].replace(status_map)
    display(orders_clean['order_status'].value_counts())
    allowed_statuses = {'completed', 'cancelled', 'refunded'}
    unexpected_statuses = orders_clean.loc[
        ~orders_clean['order_status'].isin(allowed_statuses),
        'order_status',
    ].value_counts(dropna=False)
    print('허용값 밖 order_status:')
    display(unexpected_statuses)

order_status
completed    180
cancelled     63
refunded      57
Name: count, dtype: int64

허용값 밖 order_status:

Series([], Name: count, dtype: int64)

##### 12. 날짜 컬럼 변환하기

날짜처럼 보이는 값도 실제로는 문자열일 수 있습니다. 월별 주문 분석이나 요일별 분석을 하려면 날짜형으로 변환해야 합니다.

`errors="coerce"`는 변환할 수 없는 값을 `NaT`로 바꿉니다. 그래서 변환 후 실패 건수를 반드시 확인해야 합니다.

In [16]:
orders_clean['order_date'] = pd.to_datetime(orders_clean['order_date'], errors='coerce')
print('order_date 변환 실패:', orders_clean['order_date'].isna().sum())
print('주문 시작일:', orders_clean['order_date'].min())
print('주문 종료일:', orders_clean['order_date'].max())
print('오늘 이후 주문일:', int((orders_clean['order_date'] > pd.Timestamp.today()).sum()))

orders_clean['order_month'] = orders_clean['order_date'].dt.to_period('M').astype(str)
orders_clean['order_dayofweek'] = orders_clean['order_date'].dt.day_name()

orders_clean[['order_date', 'order_month', 'order_dayofweek']].head()

order_date 변환 실패: 3
주문 시작일: 2025-07-01 00:00:00
주문 종료일: 2028-12-31 00:00:00
오늘 이후 주문일: 2

  order_date order_month order_dayofweek
0 2026-07-12     2026-07          Sunday
1 2025-10-02     2025-10        Thursday
2 2026-03-13     2026-03          Friday
3 2025-10-12     2025-10          Sunday
4 2026-04-17     2026-04          Friday

In [17]:
if 'signup_date' in customers_clean.columns:
    customers_clean['signup_date'] = pd.to_datetime(customers_clean['signup_date'], errors='coerce')
    print('signup_date 변환 실패:', customers_clean['signup_date'].isna().sum())
    display(customers_clean[['customer_id', 'signup_date']].head())

signup_date 변환 실패: 2

   customer_id signup_date
0            1  2025-10-05
1            2  2023-09-20
2            3  2025-01-22
3            4  2025-03-13
4            5  2024-02-10

##### 13. 숫자형 컬럼 변환하기

가격, 수량, 단가는 숫자처럼 보여도 문자열일 수 있습니다. 특히 `10,000`처럼 쉼표가 들어간 값은 바로 계산하기 어렵습니다.

In [18]:
def to_number(series):
    return pd.to_numeric(
        series.astype(str).str.replace(',', '', regex=False),
        errors='coerce'
    )

products_clean['price'] = to_number(products_clean['price'])
order_items_clean['quantity'] = to_number(order_items_clean['quantity'])
order_items_clean['unit_price'] = to_number(order_items_clean['unit_price'])

print('price 변환 실패:', products_clean['price'].isna().sum())
print('quantity 변환 실패:', order_items_clean['quantity'].isna().sum())
print('unit_price 변환 실패:', order_items_clean['unit_price'].isna().sum())

price 변환 실패: 2
quantity 변환 실패: 5
unit_price 변환 실패: 2

In [19]:
# 변환한 뒤 결측 처리와 처리 근거 확인
# age만 중앙값으로 대체, 금액, 수량(price, unit_price, quantity)은 일단 결측 건수만 확인
# age, city는 앞의 '8. 결측치 처리하기' 셀에서 이미 대체되었으므로 원본(customers) 기준

age_missing_before = pd.to_numeric(customers['age'], errors='coerce').isna().sum()
age_median = customers_clean['age'].median()
customers_clean['age'] = customers_clean['age'].fillna(age_median)
print('age 대체 전 결측(결측 + 변환 실패):', age_missing_before)
print('age 중앙값:', age_median)
print('age 대체 후 결측:', customers_clean['age'].isna().sum())

for df, col in [
    (products_clean, 'price'),
    (order_items_clean, 'unit_price'),
    (order_items_clean, 'quantity'),
]:
    print(f'{col} 결측(확인 필요, 보류):', df[col].isna().sum())

city_missing_before = customers['city'].isna().sum()
customers_clean['city'] = customers_clean['city'].fillna('Unknown')
gender_missing_before = customers_clean['gender'].isna().sum()
customers_clean['gender'] = customers_clean['gender'].fillna('Unknown')

print('city 대체 전 결측:', city_missing_before)
print('city 대체 후 결측:', customers_clean['city'].isna().sum())
print('gender 대체 전 결측:', gender_missing_before)
print('gender 대체 후 결측:', customers_clean['gender'].isna().sum())
print(missing_summary(customers_clean))

age 대체 전 결측(결측 + 변환 실패): 6
age 중앙값: 41.0
age 대체 후 결측: 0
price 결측(확인 필요, 보류): 2
unit_price 결측(확인 필요, 보류): 2
quantity 결측(확인 필요, 보류): 5
city 대체 전 결측: 2
city 대체 후 결측: 0
gender 대체 전 결측: 0
gender 대체 후 결측: 0
             missing_count  missing_ratio
signup_date              2           1.33
customer_id              0           0.00
name                     0           0.00
gender                   0           0.00
age                      0           0.00
city                     0           0.00

In [20]:
#문자열 변경, 변환 실패 확인
def audit_numeric(series, remove_comma=False):
    values = series.astype(str)
    if remove_comma:
        values = values.str.replace(',', '', regex=False)
    converted = pd.to_numeric(values, errors='coerce')
    return int((~series.isna() & converted.isna()).sum())

def audit_date(series):
    converted = pd.to_datetime(series, errors='coerce')
    return int((~series.isna() & converted.isna()).sum())

for name, df in raw_data.items():
    for col in df.select_dtypes(include=['object', 'str']).columns:
        present = df.loc[df[col].notna(), col].astype(str)
        stripped = present.str.strip()
        print(
            f'{name}.{col} 공백 제거 변경:',
            int((present != stripped).sum()),
            '/ 빈 문자열→결측:',
            int((stripped == '').sum()),
        )

print('age 새 변환 실패:', audit_numeric(customers['age']))
print('price 새 변환 실패:', audit_numeric(products['price'], remove_comma=True))
print('quantity 새 변환 실패:', audit_numeric(order_items['quantity'], remove_comma=True))
print('unit_price 새 변환 실패:', audit_numeric(order_items['unit_price'], remove_comma=True))
print('order_date 새 변환 실패:', audit_date(orders['order_date']))
print('signup_date 새 변환 실패:', audit_date(customers['signup_date']))

customers.name 공백 제거 변경: 0 / 빈 문자열→결측: 0
customers.gender 공백 제거 변경: 0 / 빈 문자열→결측: 0
customers.age 공백 제거 변경: 0 / 빈 문자열→결측: 0
customers.city 공백 제거 변경: 5 / 빈 문자열→결측: 0
customers.signup_date 공백 제거 변경: 0 / 빈 문자열→결측: 0
products.product_name 공백 제거 변경: 0 / 빈 문자열→결측: 0
products.category 공백 제거 변경: 3 / 빈 문자열→결측: 0
products.price 공백 제거 변경: 0 / 빈 문자열→결측: 0
orders.order_date 공백 제거 변경: 0 / 빈 문자열→결측: 0
orders.payment_method 공백 제거 변경: 5 / 빈 문자열→결측: 0
orders.order_status 공백 제거 변경: 0 / 빈 문자열→결측: 0
order_items.quantity 공백 제거 변경: 0 / 빈 문자열→결측: 0
order_items.unit_price 공백 제거 변경: 0 / 빈 문자열→결측: 0
age 새 변환 실패: 2
price 새 변환 실패: 2
quantity 새 변환 실패: 5
unit_price 새 변환 실패: 2
order_date 새 변환 실패: 3
signup_date 새 변환 실패: 2

## 2. 문자열·타입·결측 처리
- 적용한 문자열 정리: 앞 뒤 공백 제거(city 5건, category 3건, payment_method 5건), 주문 상태값 통일, 빈 문자열 결측 변환(0건), 숫자형 변환(중간에 , 들어간 경우 제거)
- 숫자 변환 대상과 실패 건수: age 2건, price 2건, quantity 5건, unit_price 2건 (새 변환 실패 기준)
- 날짜 변환 대상과 실패 건수: order_date 3건, signup_date 2건
- 결측 처리 기준:
 - age: 중앙값(41)으로 대체 (결측 4건 + 변환 실패 2건 = 6건)
 - 금액, 수량(price, unit_price, quantity): 대표값으로 대체하지 않고 확인 대상으로 보류 (이후 이상값 처리 셀의 0 초과 조건에서 함께 제외됨)
 - 범주형: Unknown 으로 처리  (ex. city 2건, gender 0건)
 - 날짜(order_date, signup_date): 변환 실패 값은 NaT로 두고 행은 삭제하지 않음

![타입과 결측 처리](images/step02_cleaning.png)

### 결과 관찰
문자열 컬럼의 앞뒤 공백을 제거한 결과, customers.city 5건, products.category 3건, orders.payment_method 5건의 값이 바뀌었다. 빈 문자열은 모든 컬럼에서 0건이었다. 숫자형으로 변환했을 때 새롭게 발생한 변환 실패는 age 2건, price 2건, quantity 5건, unit_price 2건이었다. 날짜 변환에서는 order_date 3건, signup_date 2건이 날짜로 바뀌지 않아 NaT가 되었다. order_date의 범위는 2025-07-01부터 2028-12-31까지였는데, 이 중 2건은 이후의 미래 날짜여서 이상 후보로 따로 표시해 두었다. age는 원래 결측 4건과 변환 실패 2건을 합친 6건을 중앙값 41로 대체했고, city 결측 2건은 Unknown으로 바꿨다. price 2건, unit_price 2건, quantity 5건의 결측(변환 실패)은 대체하지 않았다. gender는 결측값이 없어 Unknown 처리 전후 모두 0건으로 유지되었다.

### 나의 해석과 판단
문자열은 앞뒤 공백을 제거하고, 빈 문자열은 결측값으로 변환하도록 처리했다. 공백 때문에 같은 도시나 결제수단이 서로 다른 값으로 집계되는 것을 막기 위해서다. 숫자와 날짜는 기존 결측값과 변환 실패를 구분해서 확인했다. errors="coerce"로 변환하면 오류 없이 NaN, NaT로 바뀌기 때문에 실패 건수를 따로 세지 않으면 놓칠 수 있다고 생각했다.
age의 경우 결측값이 있으면 중앙값으로 대체하도록 했다. 숫자로 바꿀 수 없었던 2건도 실제 나이를 알 수 없는 값이므로 결측과 같이 보고 대체했다. 결측치라고 완전히 삭제해버리는 경우 결측치가 많아지면 데이터 분석에 지장이 갈 수 있으며, 그렇다고 랜덤값으로 대체하기에는 범위가 너무 넓어질 가능성이 높기 때문이다. 게다가 숫자형이므로 중앙값을 확인할 수 있고, 평균보다 극단값의 영향을 덜 받기 때문에 이를 선택했다. 반면 price, unit_price, quantity는 금액, 수량이므로 대표값으로 채우면 line_total과 금액 집계가 그대로 왜곡된다. 그래서 이 컬럼들은 결측이 있어도 대체하지 않고 확인 대상으로 보류하도록 기준을 정했다. 다만 이후 실습용 이상값 처리 기준(0 초과만 남김)을 적용하면서 이 결측 행들도 함께 분석 대상에서 빠졌다. 날짜 변환 실패는 행을 지우지 않고 NaT로 남겼다. 날짜만 모른다고 고객이나 주문 행 전체를 삭제하면 다른 컬럼의 정보까지 잃기 때문이다.
반면 city, gender 등의 범주형 값은 결측치가 있으면 Unknown으로 구분하도록 했다. 범주이기 때문에 무작위로 선택하기에는 변동성이 커지고, 직접 확인해야하기 때문이다. 대체도 정보 손실을 만들 수 있다. age 6건을 중앙값으로 대체하면 행은 유지되지만 연령 분포가 중앙에 몰리고, 그 값이 원래 결측이었다는 사실 자체가 사라진다. Unknown 2건은 별도 범주로 집계되므로 도시별 비교에서 하나의 도시처럼 해석되지 않도록 주의해야 한다.

### 업무·분석적 의미
문자열의 표기 차이나 변환 실패를 확인하지 않으면 범주별 집계, 금액 계산, 기간 분석에서 오류가 생길 수 있다. 이번 데이터에서도 공백이 섞인 값 13건, 숫자 변환 실패 11건, 날짜 변환 실패 5건이 있었다. 이를 확인하지 않았다면 같은 도시가 따로 집계되거나, 금액 계산과 월별 집계에서 일부 행이 조용히 빠지는 문제가 생겼을 것이다. 따라서 데이터 분석 전 미리 처리하고, 몇 건이 영향을 받았는지 기록해두는 것이 중요하다.

### 한계와 추가 확인 사항
변환에 실패한 값이 단순 입력 오류인지, 실제로 값을 알 수 없는 것인지는 현재 데이터만으로 판단하기 어렵다. 숫자 뒤에 단위가 붙은 경우처럼 규칙을 정하면 살릴 수 있는 값도 있을 수 있는데, 이번에는 실습 기준대로 변환 실패로 처리했다. 또한 age 대체로 연령 분포가 얼마나 달라졌는지는 직접 비교하지 않았다. 실제 업무에 적용하기 전에는 결측값이 단순 입력 누락인지 수집 과정의 오류인지 먼저 확인할 필요가 있다. 또한 미래 주문일 2건이 예약 주문인지 입력 오류인지는 확인하지 못했으므로 삭제하지 않고 후보로만 남겼다.

##### 14. 이상값 후보 확인하기

이상값은 일반적인 범위를 벗어난 값입니다. 하지만 이상값이 항상 오류는 아닙니다. 0원 상품은 이벤트 상품일 수 있고, 음수 수량은 반품을 의미할 수도 있습니다. 먼저 확인하고 기준을 정해야 합니다.

In [21]:
display(products_clean['price'].describe())
display(order_items_clean[['quantity', 'unit_price']].describe())

count    9.800000e+01
mean     2.005102e+05
std      1.001829e+06
min     -2.000000e+04
25%      5.200000e+04
50%      9.250000e+04
75%      1.527500e+05
max      9.999999e+06
Name: price, dtype: float64

         quantity     unit_price
count  758.000000     761.000000
mean     3.168865  103494.086728
std      4.159055   56969.823769
min     -1.000000       0.000000
25%      2.000000   55000.000000
50%      3.000000   96000.000000
75%      4.000000  154000.000000
max    100.000000  197000.000000

In [22]:
print('price <= 0:', len(products_clean[products_clean['price'] <= 0]))
print('quantity <= 0:', len(order_items_clean[order_items_clean['quantity'] <= 0]))
print('unit_price <= 0:', len(order_items_clean[order_items_clean['unit_price'] <= 0]))

price <= 0: 2
quantity <= 0: 3
unit_price <= 0: 1

In [23]:
print(
    'age < 0 or age > 120:',
    len(customers_clean[(customers_clean['age'] < 0) | (customers_clean['age'] > 120)]),
)

age < 0 or age > 120: 1

###### 실습용 이상값 처리 기준

이번 실습에서는 정상 주문 분석을 위해 다음 기준을 적용합니다.

```text
- age가 0 미만 또는 120 초과
- price가 0 이하인 상품은 분석 대상에서 제외
- quantity가 0 이하인 주문 상세는 분석 대상에서 제외
- unit_price가 0 이하인 주문 상세는 분석 대상에서 제외
```

실제 업무에서는 이 기준을 적용하기 전에 반드시 원본 시스템이나 담당자 확인이 필요합니다.

In [24]:
outlier_candidate_counts = {
    'age < 0 or age > 120': len(
        customers_clean[(customers_clean['age'] < 0) | (customers_clean['age'] > 120)]
    ),
    'price <= 0': len(products_clean[products_clean['price'] <= 0]),
    'quantity <= 0': len(order_items_clean[order_items_clean['quantity'] <= 0]),
    'unit_price <= 0': len(order_items_clean[order_items_clean['unit_price'] <= 0]),
}

print('이상값 후보 건수(제외 전 집계):', outlier_candidate_counts)

이상값 후보 건수(제외 전 집계): {'age < 0 or age > 120': 1, 'price <= 0': 2, 'quantity <= 0': 3, 'unit_price <= 0': 1}

In [25]:
# 제외 사유별 건수 (제외 전에 집계)
for name, df, col in [
    ('products', products_clean, 'price'),
    ('order_items', order_items_clean, 'quantity'),
    ('order_items', order_items_clean, 'unit_price'),
]:
    print(f'{name}.{col} 0 이하:', int((df[col] <= 0).sum()), '/ 숫자 변환 실패(NaN):', int(df[col].isna().sum()))

products.price 0 이하: 2 / 숫자 변환 실패(NaN): 2
order_items.quantity 0 이하: 3 / 숫자 변환 실패(NaN): 5
order_items.unit_price 0 이하: 1 / 숫자 변환 실패(NaN): 2

In [26]:
products_clean = products_clean[products_clean['price'] > 0]
order_items_clean = order_items_clean[order_items_clean['quantity'] > 0]
order_items_clean = order_items_clean[order_items_clean['unit_price'] > 0]

print('이상값 처리 후 products:', products_clean.shape)
print('이상값 처리 후 order_items:', order_items_clean.shape)

이상값 처리 후 products: (96, 4)
이상값 처리 후 order_items: (752, 5)

In [27]:
for col in ['gender', 'city']:
    print(col, customers_clean[col].unique())

for col in ['category']:
    print(col, products_clean[col].unique())

for col in ['payment_method', 'order_status']:
    print(col, orders_clean[col].unique())

gender <StringArray>
['F', 'M']
Length: 2, dtype: str
city <StringArray>
['서울', '대구', '울산', '광주', '성남', '부산', '대전', '수원', '인천', '고양', 'Unknown']
Length: 11, dtype: str
category <StringArray>
['도서', '전자기기', '패션', '스포츠', '뷰티', '생활용품', '식품', '전자 기기', '생활 용품', '뷰 티']
Length: 10, dtype: str
payment_method <StringArray>
['naver_pay', 'kakao_pay', 'bank_transfer', 'card']
Length: 4, dtype: str
order_status <StringArray>
['completed', 'cancelled', 'refunded']
Length: 3, dtype: str

In [28]:
maps = {
    'gender': {'m':'male', '남':'male', '남성':'male', 'f':'female', '여':'female', '여성':'female'},
    'payment_method': {'card':'card', '신용카드':'card', '카드':'card', '계좌이체':'bank_transfer'},
    'category': {'전자 기기':'전자기기', '생활 용품':'생활용품', '뷰 티':'뷰티'},
    'order_status': {'complete':'completed', '완료':'completed', 'cancel':'cancelled', '취소':'cancelled', '환불':'refunded'}
}

for df in [customers_clean, products_clean, orders_clean]:
    for col, mapping in maps.items():
        if col in df:
            df[col] = df[col].str.strip().str.lower().replace(mapping)

In [29]:
allowed = {
    'gender': ['female', 'male'],
    'payment_method': ['card', 'naver_pay', 'bank_transfer', 'kakao_pay'],
    'order_status': ['completed', 'cancelled', 'refunded'],
    'category': ['전자기기', '도서', '생활용품', '식품', '스포츠', '패션', '뷰티']
}

for df in [customers_clean, products_clean, orders_clean]:
    for col, ok in allowed.items():
        if col in df:
            other = df.loc[~df[col].isin(ok), col].dropna().unique()
            if len(other):
                print(f'{col}의 다른 값:', other)
            else:
                print(f'{col}: 허용값 밖 범주 없음')

gender: 허용값 밖 범주 없음
category: 허용값 밖 범주 없음
payment_method: 허용값 밖 범주 없음
order_status: 허용값 밖 범주 없음

## 3. 중복·범주 표준화·이상값 후보
- 제거/보류한 중복: 완전 중복 각 2건 제거 (customers, products, orders, order_items 총 8건). 주요 ID 중복도 같은 행이라 함께 해소됨
- 표준화한 범주값: order_status(비표준 표기 15건 → completed, cancelled, refunded), category(띄어쓰기 3건, '전자 기기', '생활 용품', '뷰 티'), city와 payment_method(공백 제거), gender(F/M → female/male)
- 허용값 밖 값: 표준화 후 0건
- 이상값 후보: age 120 초과 1건(보류), price 0 이하 2건, quantity 0 이하 3건, unit_price 0 이하 1건(실습 기준에 따라 제외)

![중복 범주 이상값](images/step03_rules.png)

### 결과 관찰
완전 중복 행은 customers, products, orders, order_items에서 각각 2건씩 있었고 drop_duplicates로 제거했다. 제거 후에는 주요 ID 중복도 0건이 되었다. order_status는 completed, cancelled, refunded 외에 Complete, cancel, 완료, 환불 등 12가지 다른 표기가 15건 있었는데, 매핑 후 completed 180건, cancelled 63건, refunded 57건으로 통일되었다. category는 공백을 제거한 뒤에도 '전자 기기', '생활 용품', '뷰 티'처럼 띄어쓰기가 다른 값이 남아 있어서 따로 매핑했다. gender는 원본의 F/M이 소문자 변환과 매핑을 거쳐 female/male로 표기가 바뀌었다. 표준화 후 허용값 밖 범주는 gender, category, payment_method, order_status 모두 0건이었다.
이상값 후보는 제외 셀을 실행하기 전에 먼저 집계했다. age가 120을 초과한 경우 1건, price가 0 이하인 경우 2건, quantity가 0 이하인 경우 3건, unit_price가 0 이하인 경우 1건이었다. 이후 실습용 이상값 처리 기준을 적용한 결과 products는 100행에서 96행으로, order_items는 763행에서 752행으로 줄었다. 0 이하 값뿐 아니라 숫자 변환에 실패한 행(price 2건, quantity 5건, unit_price 2건)도 0 초과 조건을 통과하지 못해 함께 제외되었다. age 120 초과 1건은 제외 기준에 없어서 그대로 남았다.

### 나의 해석과 판단
완전 중복 행은 모든 컬럼 값이 같으므로 같은 기록이 두 번 저장된 것으로 보고 제거했다. 주요 ID 중복 2건도 완전 중복과 같은 행이었기 때문에 따로 처리하지 않았다. 만약 ID만 같고 다른 값이 다른 경우였다면 어느 행이 맞는지 알 수 없으므로 바로 삭제하지 않고 원인을 확인했을 것이다.
범주값은 업무적으로 같은 의미라고 판단되는 것만 명시적으로 매핑했다. Complete, 완료 등은 모두 completed와 같은 의미이고, '전자 기기'와 '전자기기'도 띄어쓰기만 다른 같은 카테고리라고 보았다. gender는 원본이 이미 F/M으로 일관되어 있어 오류를 고친 것은 아니고, 다른 범주처럼 소문자 영문 단어로 표기를 맞추기 위해 female/male로 바꾼 것이다. 의미는 같아서 정보 손실은 없다. 다만 꼭 필요한 처리는 아니었고, 이 규칙이 스크립트에는 없어 Notebook 결과와 스크립트 결과가 달라지는 원인이 되었다(뒤에있음). 이후 분석에서는 어느 저장본인지에 따라 F/M 또는 female/male로 필터링해야 한다.
이상값 후보는 바로 오류로 판단하면 안 된다고 생각한다. 그 이유는 0원 상품, 음수 수량, 0원 단가는 증정품이나 반품, 프로모션 같은 정상적인 업무 상황에서도 생길 수 있는 값일 가능성이 있기 때문이다. 이번에는 공식 실습 기준에 따라 0 이하 값을 정상 주문 분석 대상에서 제외했지만, 실제 데이터라면 제외하기 전에 업무 의미를 먼저 확인하고 그 전까지는 보류했을 것이다. 또한 0 초과 조건 하나로 변환 실패 행까지 함께 빠진다는 점은 셀 결과의 행 수를 비교해보고 알 수 있었다. 이처럼 의도하지 않은 제외가 생길 수 있으므로 제외 전후 건수를 따로 세는 것이 필요하다. age 150 1건은 입력 오류일 가능성이 높아 보이지만 확인 전에는 단정할 수 없으므로 후보로 남겨두었다.

### 업무·분석적 의미
중복, 범주값, 이상값을 기준 없이 자동 처리하면 정상적인 주문 상세나 반품, 프로모션 기록까지 제거할 수 있다. 상태별 집계 결과도 달라질 수 있다. 이번에 제외된 products 4건과 order_items 11건은 이후 금액 집계에서 빠지게 되고, 상품이 제외되면 그 상품을 주문한 주문 상세와의 관계도 깨질 수 있다(4번에서 확인). 따라서 허용값과 이상값 후보 기준을 미리 정해두면 이후 같은 문제가 발생했을 때 왜 값이 변경됐는지, 어느 범위까지 영향을 받았는지 확인할 수 있다.

### 한계와 추가 확인 사항
0원 상품이나 음수 수량이 실제로 증정품이나 반품인지는 확인하지 못했다. 또한 이번 규칙은 0 이하만 후보로 보기 때문에 quantity 50, 100이나 price 9,999,999처럼 지나치게 큰 값은 걸러지지 않았다. 실제 운영 데이터에 적용할 때는 주문 상태 코드의 정의와 반품 기록 방식, 증정품이나 프로모션의 가격 처리 기준, 그리고 상한 기준을 먼저 확인해야 한다. 그 기준을 확인한 뒤 보류나 제외 여부를 결정하는 것이 적절하다.

##### 15. 파생 컬럼 만들기

전처리된 수량과 단가를 사용하면 주문 상세 금액을 계산할 수 있습니다.

`line_total = quantity × unit_price`

In [30]:
order_items_clean['line_total'] = (
    order_items_clean['quantity'] * order_items_clean['unit_price']
)

order_items_clean[['quantity', 'unit_price', 'line_total']].head()

   quantity  unit_price  line_total
0       2.0    172000.0    344000.0
1       4.0     79000.0    316000.0
2       3.0     87000.0    261000.0
3       1.0    187000.0    187000.0
4       5.0    125000.0    625000.0

In [31]:
# line_total 전체 행 검증
line_total_ok = (
    order_items_clean['line_total']
    == order_items_clean['quantity'] * order_items_clean['unit_price']
)
print('line_total 검증 행 수:', len(order_items_clean))
print('line_total 불일치 건수:', int((~line_total_ok).sum()))

line_total 검증 행 수: 752
line_total 불일치 건수: 0

In [32]:
print('전처리 후 주문 상세 금액 합계:', order_items_clean['line_total'].sum())

전처리 후 주문 상세 금액 합계: 252140000.0

##### 16. 파일 간 관계 다시 확인하기

전처리 과정에서 일부 행을 삭제하면 파일 간 관계가 깨질 수 있습니다. 예를 들어 `products`에서 일부 상품을 제외했는데 `order_items`에는 그 상품 ID가 남아 있을 수 있습니다.

In [33]:
invalid_customers = orders_clean[
    ~orders_clean['customer_id'].isin(customers_clean['customer_id'])
]

invalid_orders = order_items_clean[
    ~order_items_clean['order_id'].isin(orders_clean['order_id'])
]

invalid_products = order_items_clean[
    ~order_items_clean['product_id'].isin(products_clean['product_id'])
]

relationship_checks = pd.DataFrame({
    'check': [
        'orders.customer_id exists in customers.customer_id',
        'order_items.order_id exists in orders.order_id',
        'order_items.product_id exists in products.product_id',
    ],
    'invalid_count': [
        len(invalid_customers),
        len(invalid_orders),
        len(invalid_products),
    ],
})

relationship_checks

                                               check  invalid_count
0  orders.customer_id exists in customers.custome...              2
1     order_items.order_id exists in orders.order_id              2
2  order_items.product_id exists in products.prod...             26

In [34]:
# invalid_count 원인 확인: 원본에도 없던 ID인지, 전처리에서 제외된 ID인지 구분
print('없는 customer_id:', sorted(invalid_customers['customer_id'].unique().tolist()))
print('없는 order_id:', sorted(invalid_orders['order_id'].unique().tolist()))

removed_product_ids = set(products['product_id'].tolist()) - set(products_clean['product_id'].tolist())
print('이상값 처리로 제외된 product_id:', sorted(removed_product_ids))
print('없는 product_id 중 제외된 상품을 참조:', int(invalid_products['product_id'].isin(removed_product_ids).sum()))
print('없는 product_id 중 원본에도 없던 ID:', int((~invalid_products['product_id'].isin(products['product_id'])).sum()))
print('없는 customer_id 중 원본 customers에 있던 ID:', int(invalid_customers['customer_id'].isin(customers['customer_id']).sum()))
print('없는 order_id 중 원본 orders에 있던 ID:', int(invalid_orders['order_id'].isin(orders['order_id']).sum()))

없는 customer_id: [9991, 9992]
없는 order_id: [9991, 9992]
이상값 처리로 제외된 product_id: [18, 48, 73, 95]
없는 product_id 중 제외된 상품을 참조: 24
없는 product_id 중 원본에도 없던 ID: 2
없는 customer_id 중 원본 customers에 있던 ID: 0
없는 order_id 중 원본 orders에 있던 ID: 0

## 4. PK/FK와 파생 컬럼 재검증
- 없는 `customer_id`: 2건 (9991, 9992)
- 없는 `order_id`: 2건 (9991, 9992)
- 없는 `product_id`: 26건 (이상값 처리로 제외된 상품 참조 24건 + 원본에도 없던 ID 2건)
- 생성한 파생 컬럼: order_month, order_dayofweek, line_total
- `line_total` 검증: 전체 752행에서 수량과 단가의 곱이 `line_total`과 모두 일치했으며(불일치 0건), 전체 합계는 252,140,000원이었음.

![관계와 파생 컬럼 검증](images/step04_validation.png)

### 결과 관찰
orders.customer_id가 customers.customer_id에 없는 경우 2건, order_items.order_id가 orders.order_id에 없는 경우 2건, order_items.product_id가 products.product_id에 없는 경우 26건이었다. 원인을 확인해보니 없는 customer_id와 order_id는 모두 9991, 9992였다. customer_id 9991, 9992는 원본 customers에도 없었고, order_id 9991, 9992는 원본 orders에도 없었다. 없는 product_id 26건 중 24건은 이상값 처리에서 제외된 상품(18, 48, 73, 95)을 참조하는 주문 상세였고, 2건은 원본 products에도 없던 ID였다. order_items에는 line_total을 생성했는데, quantity와 unit_price의 곱으로 계산했다. 표본을 확인한 결과 2 × 172000은 344000, 4 × 79000은 316000으로 계산되어 산식과 일치했다. 전체 752행에 대해 quantity × unit_price와 line_total을 다시 비교해 불일치 건수는 0이었다. 전처리 후 주문 상세 금액 합계는 252140000이었다.

### 나의 해석과 판단
없는 customer_id와 order_id는 원본에도 존재하지 않는 ID였으므로 전처리 때문이 아니라 원래부터 참조가 끊긴 데이터라고 판단했다. 반면 없는 product_id 26건 중 24건은 이상값 처리에서 상품 4개를 제외하면서 새로 생긴 문제였다. 즉 전처리 과정에서 관계가 실제로 깨진 것이다.
이처럼 전처리 후 관계를 다시 검증해야 하는 이유는 전처리 과정에서 중복 행이나 이상값 행을 제거하면 주문과 주문상세처럼 서로 연결된 데이터의 관계가 깨질 수 있기 때문이다. 이번에도 상품 행이 삭제됐는데 주문상세에는 해당 상품 ID가 그대로 남아 있었다. 이런 상태로 두면 이후 병합이나 집계에서 누락이나 오류가 생길 수 있다. 그래서 전처리가 끝난 뒤에도 각 FK가 실제 PK를 참조하고 있는지 다시 확인해야 한다. 이 검증이 있어야 이후 분석 결과도 신뢰할 수 있다고 생각한다.
invalid 행은 바로 삭제하지 않고 남겨두었다. 원인이 원본 오류인지, 전처리 기준 때문인지에 따라 처리 방법이 달라져야 하기 때문이다. 또한 line_total 역시 전체 행을 다시 계산하여 산식이 맞는지 검증했다.

### 업무·분석적 의미
관계가 깨진 상태로 고객이나 주문, 상품을 병합하면 inner join에서는 해당 행이 빠지고, left join에서는 상품 정보가 비어 있는 행이 생긴다. 그래서 EDA에서 카테고리별 금액을 볼 때 이 26건을 어떻게 처리하는지에 따라 결과가 달라질 수 있다. line_total을 전체 행 기준으로 검증해 두어야 이후 금액을 계산할 때 출발점으로 사용할 수 있다.

### 한계와 추가 확인 사항
9991, 9992 같은 ID가 테스트 데이터인지 실제 누락인지는 확인하지 못했다. 또한 상품을 제외할 때 그 상품을 참조하는 주문 상세도 함께 제외할지 기준을 정하지 않았다. 그리고 line_total은 주문 상세 한 행의 수량 x 단가이므로 할인이나 배송비 등이 반영된 매출이라고 보기에는 어렵다.

##### 17. 전처리 전후 비교하기

전처리 전후 데이터 크기를 비교합니다. 행 수가 줄었다면 어떤 기준으로 줄었는지 설명할 수 있어야 하고, 열 수가 늘었다면 어떤 파생 컬럼이 추가되었는지 설명할 수 있어야 합니다.

In [35]:
processed_data = {
    'customers': customers_clean,
    'products': products_clean,
    'orders': orders_clean,
    'order_items': order_items_clean,
}

processed_shapes = pd.DataFrame({
    'dataset': list(processed_data.keys()),
    'rows': [df.shape[0] for df in processed_data.values()],
    'columns': [df.shape[1] for df in processed_data.values()],
})

comparison = raw_shapes.merge(
    processed_shapes,
    on='dataset',
    suffixes=('_raw', '_processed')
)

comparison

       dataset  rows_raw  columns_raw  rows_processed  columns_processed
0    customers       152            6             150                  6
1     products       102            4              96                  4
2       orders       302            5             300                  7
3  order_items       765            5             752                  6

In [36]:
#전처리 전후 상세 비교
def new_numeric_failure(series, remove_comma=False):
    values = series.astype(str)
    if remove_comma:
        values = values.str.replace(',', '', regex=False)
    converted = pd.to_numeric(values, errors='coerce')
    return int((~series.isna() & converted.isna()).sum())

def new_date_failure(series):
    converted = pd.to_datetime(series, errors='coerce')
    return int((~series.isna() & converted.isna()).sum())

conversion_failures = {
    'age': new_numeric_failure(customers['age']),
    'price': new_numeric_failure(products['price'], remove_comma=True),
    'quantity': new_numeric_failure(order_items['quantity'], remove_comma=True),
    'unit_price': new_numeric_failure(order_items['unit_price'], remove_comma=True),
    'order_date': new_date_failure(orders['order_date']),
    'signup_date': new_date_failure(customers['signup_date']),
}

q5_comparison = pd.DataFrame([
    {
        'dataset': name,
        'rows_before': raw_data[name].shape[0],
        'rows_after': processed_data[name].shape[0],
        'missing_before': int(raw_data[name].isna().sum().sum()),
        'missing_after': int(processed_data[name].isna().sum().sum()),
        'duplicate_before': int(raw_data[name].duplicated().sum()),
        'duplicate_after': int(processed_data[name].duplicated().sum()),
    }
    for name in raw_data
])

print(q5_comparison.to_string(index=False))
print('새 변환 실패:', conversion_failures)

    dataset  rows_before  rows_after  missing_before  missing_after  duplicate_before  duplicate_after
  customers          152         150               6              2                 2                0
   products          102          96               0              0                 2                0
     orders          302         300               0              9                 2                0
order_items          765         752               0              0                 2                0
새 변환 실패: {'age': 2, 'price': 2, 'quantity': 5, 'unit_price': 2, 'order_date': 3, 'signup_date': 2}

In [37]:
before = {
    'customers': customers, 'products': products,
    'orders': orders, 'order_items': order_items
}
after = {
    'customers': customers_clean, 'products': products_clean,
    'orders': orders_clean, 'order_items': order_items_clean
}

for name in before:
    print(
        f'{name}: 행 {len(before[name])} → {len(after[name])}, '
        f'열 {before[name].shape[1]} → {after[name].shape[1]}, '
        f'결측 {before[name].isna().sum().sum()} → {after[name].isna().sum().sum()}, '
        f'완전 중복 {before[name].duplicated().sum()} → {after[name].duplicated().sum()}'
    )

def numeric_fail(s):
    return pd.to_numeric(
        s.dropna().astype(str).str.replace(',', '', regex=False),
        errors='coerce'
    ).isna().sum()

def date_fail(s):
    return pd.to_datetime(s.dropna(), errors='coerce').isna().sum()

print('새 변환 실패:', {
    'age': numeric_fail(customers['age']),
    'price': numeric_fail(products['price']),
    'quantity': numeric_fail(order_items['quantity']),
    'unit_price': numeric_fail(order_items['unit_price']),
    'order_date': date_fail(orders['order_date']),
    'signup_date': date_fail(customers['signup_date'])
})

customers: 행 152 → 150, 열 6 → 6, 결측 6 → 2, 완전 중복 2 → 0
products: 행 102 → 96, 열 4 → 4, 결측 0 → 0, 완전 중복 2 → 0
orders: 행 302 → 300, 열 5 → 7, 결측 0 → 9, 완전 중복 2 → 0
order_items: 행 765 → 752, 열 5 → 6, 결측 0 → 0, 완전 중복 2 → 0
새 변환 실패: {'age': np.int64(2), 'price': np.int64(2), 'quantity': np.int64(5), 'unit_price': np.int64(2), 'order_date': np.int64(3), 'signup_date': np.int64(2)}

## 5. 전처리 전/후 비교
| 항목 | 처리 전 | 처리 후 | 변화 이유 |
| --- | ---: | ---: | --- |
| 행 수 | customers 152, products 102, orders 302, order_items 765 | customers 150, products 96, orders 300, order_items 752 | 완전 중복 각 2건 제거, 0 이하이거나 변환에 실패한 가격, 수량, 단가 행 제외(products 4건, order_items 11건) |
| 결측 | customers 6 (age 4, city 2), 나머지 0 | customers 2, orders 9, 나머지 0 | age 중앙값, city Unknown 대체로 줄었지만 날짜 변환 실패가 NaT로 새로 생김 (signup_date 2, order_date 3과 파생 컬럼 2개 각 3) |
| 중복 | 각 2 | 0 | 완전 중복 제거 |
| 변환 실패 | 변환 전 | 변환 시 16건 발생(age 2, price 2, quantity 5, unit_price 2, order_date 3, signup_date 2) → 남은 것은 날짜 NaT 5건 | age 2건은 중앙값 대체, price·quantity·unit_price 9건은 0 초과 조건으로 행 제외, 날짜 5건은 NaT로 두고 행 유지 |

![전처리 전후 비교](images/step05_before_after.png)

### 결과 관찰
customers는 152행에서 150행, products는 102행에서 96행, orders는 302행에서 300행, order_items는 765행에서 752행으로 줄었다. 결측은 customers가 6건에서 2건으로 줄었지만, orders는 0건에서 9건으로 늘었다. 완전 중복은 4개 데이터 모두 2건에서 0건이 되었다.
또한 orders 의 경우 열이 5열에서 7열로 증가했고, order_items는 6열로 증가했다.

### 나의 해석과 판단
행 수 감소는 모두 앞 단계의 결과로 설명할 수 있었다. customers와 orders는 완전 중복 2건만 줄었고, products는 중복 2건과 가격 문제 4건, order_items는 중복 2건과 수량, 단가 문제 11건이 줄었다. 줄어든 건수가 앞에서 확인한 중복, 이상값 후보, 변환 실패 건수와 맞기 때문에 의도한 결과라고 판단했다. orders의 결측이 늘어난 것은 order_date 변환 실패 3건이 NaT가 되고, 이 날짜로 만든 order_month, order_dayofweek도 같은 3행에서 비게 되었기 때문이다(3건 x 3컬럼 = 9건). customers에 남은 결측 2건도 signup_date 변환 실패이다. 날짜를 모르는 행을 지우지 않기로 했기 때문에 결측이 남는 것 역시 이상하지 않다고 생각했다.
그리고 orders와 order_items에서 열이 증가했는데, 이는 분석에 필요한 파생 컬럼을 추가했기 때문이다. orders는 order_month와 order_dayofweek가 추가되었고, order_items는 line_total이 추가되어 5열에서 6열로 늘었다. 따라서 증가한 열이 추가한 열의 수와 같기 때문에 이를 근거로 의도한 결과라고 볼 수 있다.

### 업무·분석적 의미
전후 비교 결과를 남겨두면 이후 EDA에서 행 수 감소나 분포 변화가 전처리 때문인지 구분할 수 있기 때문에 이를 만들어두는 것은 업무에서 중요하다. 이번처럼 행이 줄어든 경우 그 이유를 기록해 두지 않으면, 나중에 주문 건수나 금액이 원본과 다를 때 원인을 찾기 어렵다. 또한 주문 월,요일과 주문 상세 금액을 추가했는데, 이를 통해서 기간별, 요일별, 상품 단위별 분석을 추후에 진행할 수 있을 것이다.

### 한계와 추가 확인 사항
age를 중앙값으로 대체한 6건 때문에 연령 분포가 얼마나 달라졌는지는 직접 비교하지 않았다. 또한 제외된 products 4건과 order_items 11건이 실제로 오류였는지, 정상적인 업무 기록이었는지는 확인하지 못했다. 변환 실패는 변환 과정에서 처음 생기는 값이므로 처리 전 칸은 '변환 전'으로 두었다. 처리 후 칸의 16건은 원본 값을 기준으로 다시 계산한 발생 건수이고, 처리 후 데이터에 실제로 남아 있는 변환 실패는 날짜 NaT 5건이다.

##### 18. 전처리 결과 저장하기

전처리된 데이터는 `data/processed` 폴더에 저장합니다. Excel에서 한글 CSV를 바로 열 수 있도록 `utf-8-sig` 인코딩을 사용합니다.

In [38]:
customers_clean.to_csv(PROCESSED_DIR / 'customers_clean.csv', index=False, encoding='utf-8-sig')
products_clean.to_csv(PROCESSED_DIR / 'products_clean.csv', index=False, encoding='utf-8-sig')
orders_clean.to_csv(PROCESSED_DIR / 'orders_clean.csv', index=False, encoding='utf-8-sig')
order_items_clean.to_csv(PROCESSED_DIR / 'order_items_clean.csv', index=False, encoding='utf-8-sig')

list(PROCESSED_DIR.glob('*_clean.csv'))

[WindowsPath('c:/dev/llm-data-analysis-course/data/processed/customers_clean.csv'),
 WindowsPath('c:/dev/llm-data-analysis-course/data/processed/orders_clean.csv'),
 WindowsPath('c:/dev/llm-data-analysis-course/data/processed/order_items_clean.csv'),
 WindowsPath('c:/dev/llm-data-analysis-course/data/processed/products_clean.csv')]

In [39]:
# 저장 파일 존재, 크기 확인
for path in sorted(PROCESSED_DIR.glob('*_clean.csv')):
    print(path.name, path.exists(), path.stat().st_size)

customers_clean.csv True 6514
order_items_clean.csv True 24671
orders_clean.csv True 16421
products_clean.csv True 3968

##### 19. 전처리 요약 보고서 저장하기

전처리 기준과 결과를 Markdown 파일로 남겨 두면 이후 보고서 작성이 쉬워집니다.

In [40]:
summary_text = f'''# Chapter 5 데이터 전처리 요약

##### 전처리 결과 파일

- customers_clean.csv
- products_clean.csv
- orders_clean.csv
- order_items_clean.csv

##### 전처리 전후 데이터 크기

```text
{comparison.to_string(index=False)}
```

##### 파일 간 관계 점검 결과

```text
{relationship_checks.to_string(index=False)}
```

##### 주요 처리 내용

- 원본 데이터를 직접 수정하지 않고 복사본을 사용함
- 문자열 컬럼 앞뒤 공백 제거
- 고객 나이 결측치는 중앙값으로 대체
- 고객 도시 결측치는 Unknown으로 처리
- 주문 상태값 표기 통일
- 날짜 컬럼 변환 및 주문 월/요일 파생 컬럼 생성
- 가격, 수량, 단가를 숫자형으로 변환
- 0 이하 가격, 수량, 단가 확인 및 처리
- line_total 파생 컬럼 생성
- 파일 간 키 관계 재확인

##### 주의 사항

이 전처리 기준은 실습용 예시입니다. 실제 업무에서는 결측치와 이상값을 삭제하거나 대체하기 전에 원본 시스템, 수집 과정, 업무 담당자 확인이 필요합니다.
'''

report_path = REPORT_DIR / 'ch05_preprocessing_summary_notebook.md'
report_path.write_text(summary_text, encoding='utf-8')

print('요약 보고서 저장 완료:', report_path)

요약 보고서 저장 완료: c:\dev\llm-data-analysis-course\reports\ch05_preprocessing_summary_notebook.md

In [41]:
#비교용
summary_text = f'''# Chapter 5 데이터 전처리 요약

##### 전처리 결과 파일

- customers_clean.csv
- products_clean.csv
- orders_clean.csv
- order_items_clean.csv

##### 전처리 전후 데이터 크기

```text
{comparison.to_string(index=False)}
```

##### 파일 간 관계 점검 결과

```text
{relationship_checks.to_string(index=False)}
```

##### 주요 처리 내용

- 원본 데이터를 직접 수정하지 않고 복사본을 사용함
- 문자열 컬럼 앞뒤 공백 제거
- 고객 나이 결측치는 중앙값으로 대체
- 고객 도시 결측치는 Unknown으로 처리
- 주문 상태값 표기 통일
- 날짜 컬럼 변환 및 주문 월/요일 파생 컬럼 생성
- 가격, 수량, 단가를 숫자형으로 변환
- 0 이하 가격, 수량, 단가 확인 및 처리
- line_total 파생 컬럼 생성
- 파일 간 키 관계 재확인

##### 주의 사항

이 전처리 기준은 실습용 예시입니다. 실제 업무에서는 결측치와 이상값을 삭제하거나 대체하기 전에 원본 시스템, 수집 과정, 업무 담당자 확인이 필요합니다.
'''

report_path = REPORT_DIR / 'ch05_preprocessing_summary_1.md'
report_path.write_text(summary_text, encoding='utf-8')

print('요약 보고서 저장 완료:', report_path)

요약 보고서 저장 완료: c:\dev\llm-data-analysis-course\reports\ch05_preprocessing_summary_1.md

##### 20. 전처리 과정을 함수로 정리하기

전처리 코드를 한 번만 실행하고 끝내면 재사용하기 어렵습니다. 같은 데이터를 다시 받거나 처리 기준을 조금 바꾸어야 할 때는 함수로 정리된 코드가 훨씬 유용합니다.

In [42]:
def preprocess_customers(df):
    result = strip_string_columns(df)

    if 'age' in result.columns:
        result['age'] = pd.to_numeric(result['age'], errors='coerce')
        result['age'] = result['age'].fillna(result['age'].median())

    if 'city' in result.columns:
        result['city'] = result['city'].fillna('Unknown')

    if 'signup_date' in result.columns:
        result['signup_date'] = pd.to_datetime(result['signup_date'], errors='coerce')

    return result.drop_duplicates()


def preprocess_products(df):
    result = strip_string_columns(df)

    if 'price' in result.columns:
        result['price'] = to_number(result['price'])
        result = result[result['price'] > 0]

    return result.drop_duplicates()


def preprocess_orders(df):
    result = strip_string_columns(df)

    if 'order_status' in result.columns:
        result['order_status'] = result['order_status'].replace(status_map)

    if 'order_date' in result.columns:
        result['order_date'] = pd.to_datetime(result['order_date'], errors='coerce')
        result['order_month'] = result['order_date'].dt.to_period('M').astype(str)
        result['order_dayofweek'] = result['order_date'].dt.day_name()

    return result.drop_duplicates()


def preprocess_order_items(df):
    result = strip_string_columns(df)

    if 'quantity' in result.columns:
        result['quantity'] = to_number(result['quantity'])
        result = result[result['quantity'] > 0]

    if 'unit_price' in result.columns:
        result['unit_price'] = to_number(result['unit_price'])
        result = result[result['unit_price'] > 0]

    if {'quantity', 'unit_price'}.issubset(result.columns):
        result['line_total'] = result['quantity'] * result['unit_price']

    return result.drop_duplicates()

In [43]:
customers_clean_func = preprocess_customers(customers)
products_clean_func = preprocess_products(products)
orders_clean_func = preprocess_orders(orders)
order_items_clean_func = preprocess_order_items(order_items)

print(customers_clean_func.shape)
print(products_clean_func.shape)
print(orders_clean_func.shape)
print(order_items_clean_func.shape)

(150, 6)
(96, 4)
(300, 7)
(752, 6)

##### 21. 소스 모듈 사용하기

위에서 직접 작성한 전처리 함수는 `src/preprocessing.py`에도 정리되어 있습니다. 반복 작업이나 실제 프로젝트에서는 노트북 안에만 코드를 두기보다 소스 모듈로 분리하는 것이 좋습니다.

In [44]:
from src.data_loader import load_sales_data
from src.preprocessing import (
    build_preprocessing_report,
    compare_shapes,
    duplicate_summary,
    preprocess_sales_data,
    save_processed_data,
    validate_relationships,
)

module_raw_data = load_sales_data(RAW_DIR)
module_processed_data = preprocess_sales_data(module_raw_data)
module_relationship_checks = validate_relationships(module_processed_data)
module_comparison = compare_shapes(module_raw_data, module_processed_data)

module_comparison

       dataset  rows_raw  columns_raw  rows_processed  columns_processed
0    customers       152            6             150                  6
1  order_items       765            5             752                  6
2       orders       302            5             300                  7
3     products       102            4              96                  4

In [45]:
duplicate_summary(
    module_processed_data,
    key_columns={
        'customers': 'customer_id',
        'products': 'product_id',
        'orders': 'order_id',
        'order_items': 'order_item_id',
    },
)

       dataset  row_duplicate_count     key_column  key_duplicate_count
0    customers                    0    customer_id                    0
1     products                    0     product_id                    0
2       orders                    0       order_id                    0
3  order_items                    0  order_item_id                    0

In [46]:
module_relationship_checks

                                               check  invalid_count
0  orders.customer_id exists in customers.custome...              2
1     order_items.order_id exists in orders.order_id              2
2  order_items.product_id exists in products.prod...             26

##### 22. 스크립트로 한 번에 실행하기

노트북에서 한 단계씩 이해한 전처리 과정을 스크립트로도 실행할 수 있습니다. 터미널에서 프로젝트 루트 기준으로 아래 명령을 실행합니다.

```bash
python scripts/preprocess_data.py
```

이 스크립트는 전처리 결과 CSV와 요약 보고서를 자동으로 저장합니다.

In [47]:
# 저장한 Notebook 결과를 다시 읽어 검증
for name in ['customers', 'products', 'orders', 'order_items']:
    check = pd.read_csv(PROCESSED_DIR / f'{name}_clean.csv')
    print(name, check.shape, check.columns.tolist())

customers_check = pd.read_csv(PROCESSED_DIR / 'customers_clean.csv')
orders_check = pd.read_csv(PROCESSED_DIR / 'orders_clean.csv')

orders_check['order_date'] = pd.to_datetime(orders_check['order_date'], errors='coerce')
print('order_date 재변환 실패:', orders_check['order_date'].isna().sum())
print('customer_id 중복:', customers_check['customer_id'].duplicated().sum())
print('order_id 중복:', orders_check['order_id'].duplicated().sum())
print('저장된 gender 값:', customers_check['gender'].unique())
print('저장된 category 값:', pd.read_csv(PROCESSED_DIR / 'products_clean.csv')['category'].unique())

customers (150, 6) ['customer_id', 'name', 'gender', 'age', 'city', 'signup_date']
products (96, 4) ['product_id', 'product_name', 'category', 'price']
orders (300, 7) ['order_id', 'customer_id', 'order_date', 'payment_method', 'order_status', 'order_month', 'order_dayofweek']
order_items (752, 6) ['order_item_id', 'order_id', 'product_id', 'quantity', 'unit_price', 'line_total']
order_date 재변환 실패: 3
customer_id 중복: 0
order_id 중복: 0
저장된 gender 값: <StringArray>
['female', 'male']
Length: 2, dtype: str
저장된 category 값: <StringArray>
['도서', '전자기기', '패션', '스포츠', '뷰티', '생활용품', '식품']
Length: 7, dtype: str

In [48]:
# 스크립트(src/preprocessing.py) 로직 결과와 Notebook 결과의 범주값 비교
print('[Notebook] gender:', customers_clean['gender'].unique().tolist())
print('[스크립트] gender:', module_processed_data['customers']['gender'].unique().tolist())
print('[Notebook] category:', sorted(products_clean['category'].unique().tolist()))
print('[스크립트] category:', sorted(module_processed_data['products']['category'].unique().tolist()))

[Notebook] gender: ['female', 'male']
[스크립트] gender: ['F', 'M']
[Notebook] category: ['도서', '뷰티', '생활용품', '스포츠', '식품', '전자기기', '패션']
[스크립트] category: ['도서', '뷰 티', '뷰티', '생활 용품', '생활용품', '스포츠', '식품', '전자 기기', '전자기기', '패션']

## 6. 재현 가능한 전처리 확인
### 결과 관찰
- 생성된 clean CSV: customers_clean.csv, products_clean.csv, orders_clean.csv, order_items_clean.csv
- 생성된 요약 보고서: [reports/ch05_preprocessing_summary_notebook.md](reports/ch05_preprocessing_summary_notebook.md)
  - 4개의 clean CSV가 정상적으로 생성되었다.
  - 전처리 전후 데이터 크기와 파일 간 관계 점검 결과가 기록되었다.
  - customers 152 → 150행, products 102 → 96행, orders 302 → 300행, order_items 765 → 752행으로 기록되었다.
  - 파일 간 외래키 관계 점검 결과 invalid_count는 customer_id 2건, order_id 2건, product_id 26건이었다.
- `python scripts/preprocess_data.py` 재실행 결과: [reports/ch05_preprocessing_summary.md](reports/ch05_preprocessing_summary.md)
  - 입력 Raw 경로가 practice/chapter05/data/raw로 출력되어 Chapter 05 전용 데이터를 사용한 것을 확인했다.
  - 동일한 4개의 clean CSV가 다시 생성되었다.
  - customers 150행, products 96행, orders 300행, order_items 752행으로 Notebook과 동일한 데이터 크기가 확인되었다.
  - orders.customer_id, order_items.order_id, order_items.product_id에 대한 관계 점검에서도 invalid_count가 2, 2, 26으로 Notebook과 같았다.
  - 추가로 각 데이터셋의 행 중복과 기본키 중복 여부를 확인하는 항목이 포함되었으며, 모든 데이터셋에서 중복 개수가 0으로 확인되었다.
- 재실행 후 달라진 점: 데이터 크기와 관계 점검 결과는 이전과 같았고, 다시 실행한 요약 보고서에는 중복 점검 결과가 추가되었다. 제목 형식과 문장 표현에도 차이가 있었다. 그런데 스크립트와 같은 로직(src/preprocessing.py)의 결과를 확인해보니 gender는 F/M이었고, category에는 '전자 기기', '생활 용품', '뷰 티'가 그대로 남아 있었다. Notebook에서는 gender를 female/male로 바꾸고 category 띄어쓰기도 통일했지만, 스크립트(src/preprocessing.py)에는 이 규칙이 없어서 스크립트 결과에는 반영되지 않은 것이다.
- 저장 파일 확인: 4개 clean CSV 모두 존재했고, 크기도 0보다 컸다.
- 저장 결과 검증: csv 를 다시 읽어 shape, 컬럼, 주요ID중복, order_date 변환 실패를 확인했다. order_date 재변환 실패 3건은 원본에서 날짜로 바뀌지 않았던 3건과 같은 건수이다.
- 저장한 gender 값: female/male (Notebook 저장본 기준), 스크립트 결과는 F/M, category: Notebook 저장본은 7개로 통일, 스크립트 결과는 표준화 전 값이 남아 있음

![재실행 결과](images/step06_reproducible.png)

### 나의 해석과 판단
Notebook에서 전처리가 한 번 정상적으로 실행됐다는 것은 그때 당시의 실행 환경과 셀 순서에서는 원하는 결과가 나왔다는 의미다. 하지만 셀 실행 순서나 이전에 저장된 변수 상태에 따라 결과가 달라질 수 있다. 한 번 성공했다고 해서 항상 같은 결과가 나온다고 보기는 어렵다.
반면 전처리 과정을 하나의 스크립트로 만들면 정해진 순서대로 다시 실행할 수 있다. 이번에도 python scripts/preprocess_data.py를 다시 실행했을 때 데이터 크기와 파일 간 관계 점검 결과는 Notebook과 같았다. 하지만 범주 표준화 결과는 달랐다. Notebook 셀에서 추가한 규칙은 스크립트에 옮기지 않으면 재현되지 않는다는 것을 확인했다. 즉 행 수가 같다고 해서 값까지 같다고 볼 수는 없고, 저장된 값까지 비교해봐야 한다. 따라서 완전히 재현 가능하게 만들려면 Notebook에서 정한 규칙을 스크립트에도 반영해야 한다고 생각했다. 실제 데이터 분석에서도 한 번 정상적으로 실행되는 것보다 같은 입력 데이터와 같은 코드를 사용했을 때 같은 결과를 다시 얻을 수 있는지가 중요하다. 그래서 전처리 과정을 스크립트로 정리해 두는 것이 필요하다고 생각했다.

### 업무 분석적 의미
스크립트로 같은 크기의 결과를 다시 만들 수 있고, 저장본은 다시 읽어서 구조도 확인했으므로 추후 분석에서 수치가 달라지면 분석 단계에서 원인을 찾을 수 있다. 

### 한계와 추가 확인 사항
csv로 저장하고 나서 다시 컬럼의 type을 확인해야 한다. 날짜가 다시 문자열로 읽힐 수 있으므로 시작 시 order_date, signup_date를 다시 날짜형으로 변환해야 한다. 또한 스크립트 결과와 Notebook 결과를 맞추려면 src/preprocessing.py에 범주 매핑을 추가하거나, EDA 시작 시 같은 매핑을 다시 적용해야 한다.

##### 23. LLM과 함께 전처리 코드를 검토하기

LLM에게 전처리 코드를 요청할 때는 실제 고객명, 이메일, 주문 내역을 그대로 입력하지 않는 것이 좋습니다. 컬럼명, 데이터 타입, 결측치 개수, 중복 여부, 처리 목적처럼 구조화된 정보만 제공하세요.


- 사용한 LLM 프롬프트  
```text

customers 데이터 품질 요약
- rows: 152
- customer_id missing/duplicate: 0 / 2
- age missing: 4
- city missing: 2

요청:

1. age 결측치 처리 후보 비교
2. 각 방법의 장단점 설명
3. 처리 전후 검증 항목 제안

이후 
다음 전처리 코드가 안전한지 검토해 주세요.

customers["age"] = customers["age"].fillna(customers["age"].mean())
customers = customers.drop_duplicates()
orders["order_date"] = pd.to_datetime(orders["order_date"])
order_items["line_total"] = order_items["quantity"] * order_items["unit_price"]

검토 기준:
- 원본 데이터를 직접 수정하는 문제가 있는지
- 결측치 처리 방식이 적절한지
- 날짜 변환 실패를 확인하는지
- 중복 제거 기준이 충분한지
- line_total 계산 전에 숫자형 변환이 필요한지
- 더 안전한 코드로 어떻게 수정할 수 있는지
```


- LLM 답변 요약
    - age 결측치는 행을 삭제하거나 복잡한 예측 모델을 사용하는 것보다 중앙값으로 대체하는 방법을 권장함
    - 처리 전후에 결측치 개수, 기술통계량, 행 수, 분포 변화를 확인하도록 제안함
    - 원본 데이터를 유지하기 위해 전처리 전에 .copy()를 사용하도록 권장함
    - 중복을 제거할 때는 전체 행이 아니라 customer_id를 기준으로 확인하도록 제안함
    - 날짜 변환 과정에서 오류가 발생하지 않도록 pd.to_datetime(..., errors="coerce")를 사용하도록 권장함
    - line_total 계산 전 quantity와 unit_price를 숫자형으로 변환하고, 변환에 실패한 값이 있는지 확인하도록 제안함
    - 전체적으로 데이터 손실을 줄이고 원본을 보존하면서, 자료형과 처리 전후 결과를 확인하는 방향으로 전처리를 진행하도록 제안함

- 검토: 
    - age 결측값 중앙값 대체: 채택. 실제 데이터에서는 결측 4건과 변환 실패 2건, 총 6건이었다. 고객 약 150명 중 6건이라 행을 삭제하기보다는 값을 대체하는 것이 적절하다고 판단했다.
    - .copy()로 원본 보존: 채택. raw 데이터를 직접 수정하지 않는다는 실습 원칙에 따라 원본을 따로 보존한다.
    - pd.to_datetime(..., errors="coerce"): 수정 후 채택. coerce를 사용하면 변환에 실패한 값이 오류 없이 NaT로 바뀌기 때문에, coerce만 쓰고 끝내지 않고 변환 후 실패 건수와 날짜 범위를 함께 확인했다. 실제로 order_date 3건, signup_date 2건이 실패했다.
    - line_total 계산 전 숫자형 변환: 채택. 계산 전에 숫자형으로 변환하고 변환실패한 값이 있는지도 함께 확인한다. 실제로 quantity 5건, unit_price 2건이 숫자로 변환되지 않았다.
    - customer_id 기준 중복 제거: 보류. 키 중복은 바로 삭제하지 않고 원인을 먼저 확인해야 한다. 이번 데이터의 customer_id 중복 2건은 모든 값이 같은 완전 중복이어서 전체 행 기준 중복 제거로 함께 해소되었다.
    - 이상값 처리 및 관계 재검증: LLM 답변에는 이 부분이 없었다. 그래서 실습 기준을 그대로 적용했다. 이상값 후보 건수를 제외 전에 먼저 확인했고, 전처리 후 PK/FK 관계를 다시 확인해 상품 제외로 깨진 관계 24건을 찾았다.
    - LLM 답변은 참고용으로 사용했다. 최종 처리 방법은 실제 데이터 출력 결과와 실습 기준을 비교한 뒤 직접 결정했다.

##### 24. 실습 과제

아래 과제를 직접 해결해 보세요.

1. 각 데이터셋의 결측치 비율을 하나의 표로 합쳐 보세요.
2. `customers_clean`에서 나이가 18세 미만이거나 100세 초과인 값이 있는지 확인하세요.
3. `orders_clean`에서 월별 주문 건수를 계산하세요.
4. `order_items_clean`에서 `line_total`이 큰 순서대로 상위 10개를 확인하세요.
5. 전처리 전후 행 수가 줄어든 데이터셋이 있는지 설명해 보세요.
6. LLM에게 결측치 처리 기준을 검토해 달라는 프롬프트를 직접 작성해 보세요.

In [49]:
# 준비
from pathlib import Path
import sys
import pandas as pd

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from src.data_loader import load_sales_data
from src.preprocessing import preprocess_sales_data

raw_data = load_sales_data(RAW_DIR)
processed_data = preprocess_sales_data(raw_data)

customers_clean = processed_data['customers']
products_clean = processed_data['products']
orders_clean = processed_data['orders']
order_items_clean = processed_data['order_items']

print('24번 실습과제 전처리 상태 준비 완료')

24번 실습과제 전처리 상태 준비 완료

In [50]:
# 과제 1. 각 데이터셋의 결측치 비율을 하나의 표로 합쳐 보세요.
# hint: missing_summary(df).reset_index()를 활용해 보세요.

missing_ratio_table = pd.concat(
    [
        pd.DataFrame(
            {
                'dataset': name,
                'column': df.columns,
                'missing_count': df.isna().sum().to_numpy(),
                'missing_ratio_pct': (df.isna().mean() * 100).round(2).to_numpy(),
            }
        )
        for name, df in processed_data.items()
    ],
    ignore_index=True,
)

print('검증 대상 컬럼 수:', len(missing_ratio_table))
print('최대 결측 수:', int(missing_ratio_table['missing_count'].max()))
print('최대 결측 비율(%):', float(missing_ratio_table['missing_ratio_pct'].max()))
missing_ratio_table

검증 대상 컬럼 수: 23
최대 결측 수: 3
최대 결측 비율(%): 1.33

        dataset           column  missing_count  missing_ratio_pct
0     customers      customer_id              0               0.00
1     customers             name              0               0.00
2     customers           gender              0               0.00
3     customers              age              0               0.00
4     customers             city              0               0.00
5     customers      signup_date              2               1.33
6      products       product_id              0               0.00
7      products     product_name              0               0.00
8      products         category              0               0.00
9      products            price              0               0.00
10       orders         order_id              0               0.00
11       orders      customer_id              0               0.00
12       orders       order_date              3               1.00
13       orders   payment_method              0               0.00
14       orders     order_status              0               0.00
15       orders      order_month              3               1.00
16       orders  order_dayofweek              3               1.00
17  order_items    order_item_id              0               0.00
18  order_items         order_id              0               0.00
19  order_items       product_id              0               0.00
20  order_items         quantity              0               0.00
21  order_items       unit_price              0               0.00
22  order_items       line_total              0               0.00

In [51]:
# 과제 2. customers_clean에서 나이가 18세 미만이거나 100세 초과인 값이 있는지 확인하세요.
age_outlier_18_100 = customers_clean.loc[
    (customers_clean['age'] < 18) | (customers_clean['age'] > 100)
]

age_condition_verified = (
    (age_outlier_18_100['age'] < 18) | (age_outlier_18_100['age'] > 100)
).all()
print('나이 18세 미만 또는 100세 초과 건수:', len(age_outlier_18_100))
print('추출 행의 조건 일치:', bool(age_condition_verified))
age_outlier_18_100

나이 18세 미만 또는 100세 초과 건수: 1
추출 행의 조건 일치: True

    customer_id name gender    age city signup_date
32           33  권승윤      F  150.0   고양  2025-09-14

In [52]:
# 과제 3. orders_clean에서 월별 주문 건수를 계산하세요.
monthly_order_counts = (
    orders_clean.groupby('order_month')
    .size()
    .rename('order_count')
    .reset_index()
    .sort_values('order_month')
)

print('월 수:', len(monthly_order_counts))
print('월별 주문 건수 합계:', int(monthly_order_counts['order_count'].sum()))
print('orders 행 수와 합계 일치:', int(monthly_order_counts['order_count'].sum()) == len(orders_clean))

nat_count = int(orders_clean['order_date'].isna().sum())
print('날짜가 없어 월에 배정되지 않은 주문:', nat_count, '/ 월별 합계 + 날짜 결측 = orders 행 수:', int(monthly_order_counts['order_count'].sum()) + nat_count == len(orders_clean))

monthly_order_counts

월 수: 16
월별 주문 건수 합계: 297
orders 행 수와 합계 일치: False
날짜가 없어 월에 배정되지 않은 주문: 3 / 월별 합계 + 날짜 결측 = orders 행 수: True

   order_month  order_count
0      2025-07           19
1      2025-08           26
2      2025-09           12
3      2025-10           22
4      2025-11           23
5      2025-12           23
6      2026-01           26
7      2026-02           19
8      2026-03           22
9      2026-04           26
10     2026-05           20
11     2026-06           24
12     2026-07           12
13     2026-08           21
14     2027-01            1
15     2028-12            1

In [53]:
# 과제 4. order_items_clean에서 line_total이 큰 순서대로 상위 10개를 확인하세요.
top10_line_total = (
    order_items_clean[
        ['order_item_id', 'order_id', 'product_id', 'quantity', 'unit_price', 'line_total']
    ]
    .sort_values('line_total', ascending=False)
    .head(10)
)

line_total_recalculated = top10_line_total['quantity'] * top10_line_total['unit_price']
print('상위 행 수:', len(top10_line_total))
print('내림차순 정렬 검증:', top10_line_total['line_total'].is_monotonic_decreasing)
print('quantity × unit_price 산식 일치:', top10_line_total['line_total'].equals(line_total_recalculated))
print('상위 10개 line_total 합계:', int(top10_line_total['line_total'].sum()))
top10_line_total

상위 행 수: 10
내림차순 정렬 검증: True
quantity × unit_price 산식 일치: True
상위 10개 line_total 합계: 27985000

     order_item_id  order_id  product_id  quantity  unit_price  line_total
750            751       295          31     100.0    155000.0  15500000.0
737            738       290          96      50.0     96000.0   4800000.0
319            320       129          23       5.0    197000.0    985000.0
9               10         5          65       5.0    193000.0    965000.0
24              25        11          65       5.0    193000.0    965000.0
293            294       119          36       5.0    193000.0    965000.0
116            117        51          65       5.0    193000.0    965000.0
20              21         9          36       5.0    193000.0    965000.0
290            291       117          47       5.0    188000.0    940000.0
491            492       195          99       5.0    187000.0    935000.0

In [54]:
#전처리 전후 행수 비교
row_count_comparison = pd.DataFrame(
    [
        {
            'dataset': name,
            'rows_before': raw_data[name].shape[0],
            'rows_after': processed_data[name].shape[0],
            'row_change': processed_data[name].shape[0] - raw_data[name].shape[0],
        }
        for name in raw_data
    ]
)

print('행 수 감소 데이터셋 수:', int((row_count_comparison['row_change'] < 0).sum()))
print('전후 총 행 수:', int(row_count_comparison['rows_before'].sum()), '->', int(row_count_comparison['rows_after'].sum()))
row_count_comparison

행 수 감소 데이터셋 수: 4
전후 총 행 수: 1321 -> 1298

       dataset  rows_before  rows_after  row_change
0    customers          152         150          -2
1     products          102          96          -6
2       orders          302         300          -2
3  order_items          765         752         -13

결론적으로 4개 데이터셋 모두 행 수가 줄었다(총 1321행 → 1298행). customers와 orders는 완전 중복 2건씩, products는 완전 중복 2건과 가격이 0 이하이거나 숫자로 변환되지 않은 4건, order_items는 완전 중복 2건과 수량이나 단가가 0 이하이거나 숫자로 변환되지 않은 11건이 빠졌기 때문이다.

6. LLM에게 결측치 처리 기준을 검토해 달라는 프롬프트를 직접 작성해 보세요.

다음은 온라인 쇼핑몰 데이터 전처리 품질 요약이다. (ch05_preprocessing_summary.md 제공)

다음 전처리 기준을 검토해라. 

1. age 결측은 중앙값으로 대체하고 city 결측은 Unknown으로 처리하는 기준의 장단점을 설명
2. 이상치를 자동 삭제하지 않고 업무 의미를 먼저 확인해야 하는 이유를 설명(내 데이터에 맞게)
3. 처리 전후에 다시 확인해야 할 결측, 중복, 변환 실패, PK/FK 관계 검증 항목을 제안
-실제 업무 의미를 확인하지 않은 값은 오류라고 단정하지 말 것

(참고: AI 답변 요약, 작성까지만 하라고 되어있어 추가적인 과제 작성은 진행하지 않았습니다)
온라인 쇼핑몰 데이터 전처리 품질 요약에 대한 검토 내용을 핵심만 요약해 드립니다.

* **1. 결측치 대체 기준의 장단점**
* **나이(Age) 중앙값 대체:** 행(Row)을 보존하고 극단값의 영향을 줄이는 장점이 있으나, 데이터 분산 축소 및 상관관계 왜곡 가능성이 있음.
* **도시(City) `Unknown` 처리:** 데이터를 버리지 않고 전체 규모를 유지해 분석할 수 있으나, 지역별 분석 시 지리적 인사이트를 흐릴 수 있음.
* **2. 이상치를 자동 삭제하지 않고 업무 의미를 먼저 확인해야 하는 이유**
* 가격이나 수량이 0 이하인 데이터는 시스템 오류뿐만 아니라 **무료 프로모션, 사은품 증정, 환불 및 반품** 등 정상적인 비즈니스 활동일 수 있으므로, 무작정 삭제하면 분석 결과가 왜곡됨.

* **3. 전처리 전후 검증 항목**
* **결측치:** 의도한 대로 값(중앙값, `Unknown`)이 잘 채워졌는지 확인.
* **중복:** 주요 고유 키에 중복이나 의도치 않은 행 복제가 발생했는지 점검.
* **변환 실패:** 데이터 타입 변환 과정에서 값이 누락되거나 에러가 발생하지 않았는지 확인.
* **PK/FK 관계:** 파일 간 불일치 항목(고아 데이터)을 단순 오류로 단정하지 말고 원본 시스템 및 업무적 맥락을 파악하여 검증.

##### 25. 정리

이번 장에서는 다음 내용을 실습했습니다.

- 원본 데이터와 전처리 데이터 분리
- 결측치 개수와 비율 확인
- 나이 결측치 중앙값 대체, 도시 결측치 Unknown 처리
- 중복 행과 주요 ID 중복 점검
- 문자열 앞뒤 공백 제거와 상태값 표기 통일
- 날짜형 변환과 주문 월/요일 파생 컬럼 생성
- 숫자형 변환과 변환 실패 건수 확인
- 이상값 후보 확인과 실습용 처리 기준 적용
- 주문 상세 금액 `line_total` 생성
- 파일 간 키 관계 재확인
- 전처리 결과 CSV와 요약 보고서 저장
- 전처리 함수를 `src/preprocessing.py` 소스 모듈로 분리

다음 장에서는 전처리된 데이터를 바탕으로 탐색적 데이터 분석, 즉 EDA를 수행합니다.

## 7. Chapter 05 최종 판단
### 내가 정한 전처리 원칙 3가지
1. 원본 데이터는 그대로 두고 복사본에서 전처리를 진행한다. 처리 전후에는 행, 열 수, 결측값, 완전 중복, 키 관계를 같은 기준으로 확인하고 기록한다.
2. 문자열을 먼저 정리한 뒤 숫자와 날짜는 errors="coerce"로 변환한다. 이때 기존 결측값과 변환 과정에서 새로 발생한 실패값을 구분해서 확인한다.
3. 이상값 후보는 바로 오류로 판단하지 않는다. 후보를 먼저 기록하고, 업무적인 의미를 확인하기 전에는 보류한다. 

### 가장 위험하다고 생각한 자동 처리 1가지와 이유
가장 주의해야 할 자동 처리는 이상치를 일괄적으로 모두 삭제하는 것이라고 생각한다. 예를 들어 이번 실습의 경우 0 이하의 가격, 수량, 단가를 모두 삭제하는 것이다. 이런 경우 실제 데이터에서는 0원 상품이 증정품이나 프로모션일 수 있고, 음수 수량은 반품을 의미할 수도 있다. 이런 값을 바로 삭제하면 정상적인 업무 기록까지 사라진다. 상품 수요나 반품률, 금액 집계 결과도 달라질 수 있다. 이번 실습에서도 0 초과 조건 하나로 0 이하 값뿐 아니라 숫자 변환에 실패한 행까지 함께 빠졌고, 상품 4개가 제외되면서 주문 상세 24건의 상품 관계가 깨졌다. 자동 처리 한 줄이 의도하지 않은 범위까지 영향을 준 것이다.
따라서 이런 값은 먼저 이상값 후보로 표시해 두는 것이 필요할 것이다. 이후 상태 코드와 주문 정책을 확인하고, 필요한 경우 담당자에게 확인한 뒤 실제 오류인지 정상적인 업무 기록인지 구분해야 한다.

### 다음 EDA에서 특히 주의할 데이터 특성

orders의 날짜 범위와 주문 상태별 분포를 먼저 확인해야 한다. 취소와 환불 주문을 집계에 포함할지도 기준을 정해두어야 한다. order_date가 NaT인 3건은 월별 집계에서 빠지기 때문에 월별 주문 건수 합계(297건)가 전체 주문 수(300건)와 다르다. 또한 2027-01, 2028-12처럼 미래 날짜가 있어 기간 범위를 정할 때 주의해야 한다.

관계가 끊긴 주문 상세(product_id 26건, order_id 2건)와 주문(customer_id 2건)을 병합에 포함할지도 정해야 한다. 그리고 processed CSV는 마지막에 Notebook과 스크립트 중 무엇을 실행했느냐에 따라 범주값이 달라질 수 있다. 따라서 EDA 시작 시 범주값을 다시 확인해야 한다.

그리고 line_total 값에 유의해야 한다. line_total은 주문 상세 한 행의 quantity × unit_price로 계산한 값이다. 할인, 세금, 배송비, 환불 등이 반영된 매출이나 순매출이라고 단정할 수는 없다. 특히 quantity 100, 50인 행이 line_total 상위 1, 2위(15,500,000, 4,800,000)를 차지하고 있어서, 합계나 평균을 볼 때 이 값들이 결과를 크게 끌어올릴 수 있다. 따라서 EDA에서는 주문 단위와 주문상세 단위를 구분하고, 상태와 기간, 반품 기준에 따라 어떤 데이터를 집계했는지 명확히 해야 한다.

### 현재 전처리의 한계
이번 전처리에서는 실습 기준에 따라 0 이하이거나 변환에 실패한 가격, 수량, 단가 행을 제외했지만, 그 값들이 실제로 오류인지 정상적인 업무 기록인지는 확인하지 못했다. 반대로 quantity 100이나 price 9,999,999처럼 큰 값, age 150, 미래 주문일은 후보로만 남겨두고 처리하지 않았다. 또한 age 결측 6건을 중앙값으로 대체했을 때 연령 분포가 어떻게 변하는지, 그것이 적절한지는 직접 비교하지 않았다. 마지막으로 Notebook에서 추가한 범주 표준화 규칙이 스크립트에는 없어서, 지금 상태로는 Notebook 결과와 스크립트 결과가 완전히 같지 않다.

## 최종 제출 체크
- [x] raw 원본을 덮어쓰지 않았습니다.
- [x] 처리 전/후 비교를 남겼습니다.
- [x] 처리 기준과 이유를 자신의 말로 작성했습니다.
- [x] clean CSV와 재실행 결과를 확인했습니다.
- [x] 개인정보/Secret이 없습니다.
- [x] `chapter05/chapter05.ipynb`가 GitHub에서 정상 표시됩니다.
- [x] 최종 Notebook 파일 URL을 제출합니다.